baseURL = "https://ripper-pedro.github.io/RipperBlog/"
title = "Pedro Ripper"
theme = "lumenveil"
locale = "en"
defaultContentLanguage = "pt-br"
enableEmoji = true

[pagination]
pagerSize = 6

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Pedro Ripper"
description = "Pedro's personal website"
keywords = "blog, developer, maker, portfolio"
info = ["Engenheiro", "Maker", "Desenvolvedor"]
avatarURL = "images/avatar.jpg"
dateFormat = "January 2, 2006"
since = 2026
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customCSS = ["css/custom.css"]
customSCSS = []
customJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# --- SOCIAL NETWORKS ---
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/ripper-pedro/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/seu-linkedin/"

# --- MENU AND LANGUAGE: ENGLISH ---
[languages.en]
label = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact"
weight = 4
url = "contact/"

# --- MENU AND LANGUAGE: PORTUGUESE ---
[languages.pt-br]
label = ":brazil:"
title = "Pedro Ripper"

[languages.pt-br.params]
author = "Pedro Ripper"
info = "Engenheiro e Maker"
description = "Site pessoal de Pedro Ripper"

[[languages.pt-br.menu.main]]
name = "Sobre"
weight = 1
url = "about/"

[[languages.pt-br.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.pt-br.menu.main]]
name = "Projetos"
weight = 3
url = "projects/"

[[languages.pt-br.menu.main]]
name = "Contato"
weight = 4
url = "contact/"

[caches.images]
dir = ':cacheDir/images'